### ISSUE TITLE
Problem with CDN

### ISSUE THREAD

**Issue by BlackStar1991** [web-padawan/vanilla-colorful#13] opened 2020-09-23 07:30 UTC
I tryed add element from CDN <script type="module" src="https://unpkg.com/vanilla-colorful?module"></script> 
and get problem on FF browser http://prntscr.com/uma6a1 // and unfortunately, I still could not get to display the value of the current color of picker

**Comment by web-padawan** [comment] 2020-09-23 07:54
Hi, can you please try to reproduce the issue with this example? https://jsbin.com/lejamix/edit?html,js,console,output

Also, what Firefox version do you have? I'm unable to reproduce this with Firefox 81.

**Comment by BlackStar1991** [comment] 2020-09-23 08:41
I used your element in this way https://jsbin.com/mujirujuqi/edit?html,js,console,output   I have FF 80.0.1

23 сентября 2020, 10:55:01, от "Serhii Kulykov" <notifications@github.com>:

**Comment by web-padawan** [comment] 2020-09-23 12:24
If you have `script type="module"` loading from CDN, then you don't need to use `import 'vanilla-colorful';` in your code.

**Comment by BlackStar1991** [comment] 2020-09-23 17:26
Thanks for the help.
Просто тестировал решение из документации. Раньше не работал с кастомными элементами 


23 сентября 2020, 15:25:01, от "Serhii Kulykov" <notifications@github.com>:

**Comment by web-padawan** [comment] 2020-09-28 16:17
I have added a section regarding ES modules in #15 to clarify using bare module specifiers. Hope this helps a bit.

Closing as answered, feel free to comment if something in the documentation isn't clear.

**Closed by web-padawan** 2020-09-28 16:17 UTC
Labels: question
